apiVersion: v1
kind: Secret
metadata:
  name: "{{ kube_resource_name }}-env"
  namespace: {{ env }}
  labels:
    {{ kube_resource_labels | to_nice_yaml(indent=2) | indent(4) }}
type: Opaque
data:
  DATABASE_PASSWORD: "{{ 'not_very_secret_a' | b64encode }}"
